# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("http://localhost:3000/index.html")
    self.driver.set_window_size(805, 690)
    self.driver.find_element(By.ID, "myCheck").click()
    self.driver.find_element(By.LINK_TEXT, "Page 2").click()
    self.driver.find_element(By.LINK_TEXT, "Page 3").click()
    self.driver.find_element(By.LINK_TEXT, "Page 1").click()
    self.driver.find_element(By.LINK_TEXT, "Page 3").click()
    self.driver.find_element(By.LINK_TEXT, "Page 4").click()
    self.driver.find_element(By.LINK_TEXT, "Page 2").click()
    self.driver.find_element(By.LINK_TEXT, "Page 1").click()
    self.driver.find_element(By.ID, "myCheck").click()
    self.driver.find_element(By.LINK_TEXT, "Page 3").click()
    self.driver.find_element(By.LINK_TEXT, "Page 4").click()
    self.driver.find_element(By.LINK_TEXT, "Page 3").click()
    self.driver.find_element(By.LINK_TEXT, "Page 4").click()
    self.driver.find_element(By.LINK_TEXT, "Page 2").click()
    self.driver.find_element(By.LINK_TEXT, "Page 3").click()
    self.driver.find_element(By.LINK_TEXT, "Page 1").click()
    self.driver.find_element(By.LINK_TEXT, "Page 2").click()
  
